# Generated by Django 5.1.5 on 2025-01-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('nickname', models.CharField(max_length=200)),
                ('skills', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
