# Generated by Django 5.1.5 on 2025-02-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0002_scrumuser_delete_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumuser',
            name='id',
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='uid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='User Id'),
            preserve_default=False,
        ),
    ]
