# Generated by Django 5.1.5 on 2025-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0003_remove_scrumuser_id_scrumuser_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumuser',
            old_name='nickname',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='scrumuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scrumuser',
            name='username',
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='assigned_tickets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='num_tickets',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='project',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumuser',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
