# Generated by Django 5.1.5 on 2025-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0004_rename_nickname_scrumuser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumuser',
            name='assigned_tickets',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scrumuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrumuser',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
