# Generated by Django 5.1.5 on 2025-02-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0005_alter_scrumuser_assigned_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumuser',
            name='num_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrumuser',
            name='project',
            field=models.IntegerField(default=-1),
        ),
    ]
