# Generated by Django 5.1.6 on 2025-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0006_alter_scrumuser_num_tickets_alter_scrumuser_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumuser',
            name='num_tickets',
        ),
        migrations.RemoveField(
            model_name='scrumuser',
            name='project',
        ),
        migrations.AlterField(
            model_name='scrumuser',
            name='assigned_tickets',
            field=models.JSONField(default=dict),
        ),
    ]
