# Generated by Django 5.1.6 on 2025-02-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20230328_1430'),
        ('user_projects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserInvite',
            fields=[
                ('invitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invitations.invitation')),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('invitations.invitation',),
        ),
        migrations.AlterField(
            model_name='userfullmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
