# Generated by Django 5.1.6 on 2025-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfullmodel',
            name='num_tickets',
        ),
        migrations.AlterField(
            model_name='userfullmodel',
            name='assigned_tickets',
            field=models.JSONField(default=dict),
        ),
    ]
