# Generated by Django 5.1.5 on 2025-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ticket Id')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('story_points', models.IntegerField(default=0)),
                ('creator', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('date_created', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.CharField(default='', max_length=100)),
                ('date_assigned', models.CharField(default='', max_length=100)),
                ('project', models.IntegerField()),
                ('assigned', models.BooleanField(default=False)),
            ],
        ),
    ]
