# Generated by Django 5.1.7 on 2025-03-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False, verbose_name='Ticket Id')),
                ('title', models.CharField(default='New Ticket', max_length=100)),
                ('description', models.CharField(default='No description', max_length=500)),
                ('assigned', models.IntegerField(default=-1)),
                ('story_points', models.IntegerField(default=0)),
                ('creator', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField()),
                ('date_assigned', models.DateTimeField()),
                ('project', models.IntegerField()),
            ],
        ),
    ]
