# Generated by Django 5.1.6 on 2025-02-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFullModel',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='User Id')),
                ('assigned_tickets', models.JSONField(default=list)),
                ('project', models.IntegerField(default=-1)),
                ('num_tickets', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('skills', models.JSONField(default=list)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
