# Generated by Django 5.1.6 on 2025-02-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_userfullmodel_userloginmodel_delete_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfullmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userfullmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
