# Generated by Django 5.1.6 on 2025-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_userfullmodel_last_login_alter_userfullmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfullmodel',
            name='num_tickets',
        ),
        migrations.AlterField(
            model_name='userfullmodel',
            name='assigned_tickets',
            field=models.JSONField(default=dict),
        ),
    ]
