# Generated by Django 5.1.6 on 2025-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectShell',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Project Id')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('tickets', models.JSONField(default=list)),
                ('creator', models.IntegerField()),
                ('date_created', models.CharField(max_length=100)),
                ('scrum_users', models.JSONField(default=list)),
                ('admin', models.JSONField(default=list)),
            ],
        ),
    ]
