# Generated by Django 5.1.7 on 2025-03-29 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20230328_1430'),
        ('projectControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserInvite',
            fields=[
                ('invitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invitations.invitation')),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('invitations.invitation',),
        ),
        migrations.CreateModel(
            name='ProjectTicketAssignmentModel',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ticket Id')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('assigned', models.IntegerField(default=-1)),
                ('story_points', models.IntegerField(default=0)),
                ('creator', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(null=True)),
                ('date_assigned', models.DateTimeField(null=True)),
                ('project', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFullModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='User Id')),
                ('assigned_tickets', models.JSONField(default=dict)),
                ('project', models.IntegerField(default=-1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('skills', models.JSONField(default=list)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
