# Generated by Django 5.1.6 on 2025-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFullModel',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ticket Id')),
                ('project', models.IntegerField(verbose_name='Project')),
                ('story_points', models.IntegerField(verbose_name='Project')),
                ('creator', models.IntegerField(verbose_name='Creator')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('assigned_to', models.IntegerField(verbose_name='Assigned_to')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('completed', models.BooleanField(verbose_name='Completed')),
                ('assigned', models.BooleanField(verbose_name='Completed')),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('date_completed', models.DateTimeField(verbose_name='Date Completed')),
                ('date_assigned', models.DateTimeField(verbose_name='Date Assigned')),
            ],
        ),
    ]
