from django.shortcuts import render
import requests
import time

from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status

from .serializers import *


# Create your views here.
@api_view(['POST'])
def signup_handler(request):
    if request.method == 'POST':
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            
            # Check if user exists

            attempts = 0 # attempts to reach ISCS
            while attempts <= 5:
                #TODO configure URL for ISCS
                url = ""
                #TODO How is User ID decided? is ID generated by frontend?
                id = 0
                #TODO Confirm endpoint for Login/Sign-Up
                response = requests.get(url + f"/user/{id}")

                if response.status_code == 404: # Account does not exist
                    # Send Data to UserService through ISCS

                    payload = request.data
                    response = requests.post(url + f"/user", payload)

                    # Send 201 back
                    return Response(status=status.HTTP_201_CREATED)
                
                elif response.status_code == 200: # Account exists
                    # Send 409 error back to frontend
                    
                    return Response(status=status.HTTP_409_CONFLICT)

                else: # Error in accesing ISCS or UserService
                    attempts += 1
                    time.sleep(5)
            # After 5 attempts send back response from UserService
            return Response({"error": "Request failed"}, status=response.status_code)
        # Data formatted wrong
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    # wrong request method
    else:
        return Response({"error": "Method not allowed"}, status=status.HTTP_400_BAD_REQUEST)
