# Generated by Django 5.1.5 on 2025-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.JSONField(default=list),
        ),
    ]
