# Generated by Django 5.1.6 on 2025-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_services', '0002_alter_project_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(),
        ),
    ]
