# Generated by Django 5.1.6 on 2025-03-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_services', '0003_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
