# Generated by Django 5.1.6 on 2025-03-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_services', '0004_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Project Id'),
        ),
    ]
